#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build small JSON shards for GitHub Pages/Cloudflare Pages deployment.

The browser still passes the same JSON arrays to translate_core.load_data(),
but app.js can download them as many smaller cacheable files instead of two
large assets. This keeps every deployed asset comfortably below common static
hosting limits and makes future growth safer.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
OUT_ROOT = DATA_DIR / "shards"
MAX_SHARD_BYTES = 600 * 1024
SOURCES = {
    "dictionary": DATA_DIR / "dictionary.json",
    "overrides": DATA_DIR / "overrides.json",
}


def compact_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def load_array(path: Path) -> list[Any]:
    with path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, list):
        raise TypeError(f"{path} must contain a JSON array")
    return data


def clean_out_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    for old in path.glob("*.json"):
        old.unlink()


def write_shard(out_dir: Path, stem: str, index: int, item_texts: list[str]) -> dict[str, Any]:
    rel_name = f"{index:03d}.json"
    text = "[" + ",".join(item_texts) + "]\n"
    out_path = out_dir / rel_name
    out_path.write_text(text, encoding="utf-8")
    return {
        "path": f"{stem}/{rel_name}",
        "items": len(item_texts),
        "bytes": len(text.encode("utf-8")),
    }


def build_shards(stem: str, source: Path) -> dict[str, Any]:
    data = load_array(source)
    out_dir = OUT_ROOT / stem
    clean_out_dir(out_dir)

    shards: list[dict[str, Any]] = []
    current: list[str] = []
    current_bytes = 2  # []

    for item in data:
        item_text = compact_json(item)
        item_bytes = len(item_text.encode("utf-8"))
        extra = item_bytes + (1 if current else 0)  # comma before item
        if current and current_bytes + extra > MAX_SHARD_BYTES:
            shards.append(write_shard(out_dir, stem, len(shards), current))
            current = []
            current_bytes = 2
            extra = item_bytes
        current.append(item_text)
        current_bytes += extra

    if current or not data:
        shards.append(write_shard(out_dir, stem, len(shards), current))

    return {
        "source": f"../{source.name}",
        "items": len(data),
        "sourceBytes": source.stat().st_size,
        "sourceSha256": sha256_file(source),
        "shards": shards,
    }


def main() -> None:
    OUT_ROOT.mkdir(parents=True, exist_ok=True)
    manifest: dict[str, Any] = {
        "schema": 1,
        "description": "Generated by scripts/build_data_shards.py. Do not edit shard files by hand.",
        "maxShardBytes": MAX_SHARD_BYTES,
    }
    for stem, source in SOURCES.items():
        manifest[stem] = build_shards(stem, source)

    manifest_text = json.dumps(manifest, ensure_ascii=False, indent=2) + "\n"
    (OUT_ROOT / "manifest.json").write_text(manifest_text, encoding="utf-8")

    print(f"Wrote {OUT_ROOT / 'manifest.json'}")
    for stem in SOURCES:
        section = manifest[stem]
        total = sum(s["bytes"] for s in section["shards"])
        print(f"{stem}: {section['items']} items, {len(section['shards'])} shards, {total} bytes")


if __name__ == "__main__":
    main()
